// <auto-generated />
namespace Diet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedcattomessageboard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcattomessageboard));
        
        string IMigrationMetadata.Id
        {
            get { return "201811192004538_added cat to messageboard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
